# Generated by Django 5.2.5 on 2025-09-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_sitesetting'),
        ('courses', '0002_courseinstructor_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor_departments',
            field=models.ManyToManyField(blank=True, related_name='instructor_users', to='courses.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='instructor_specializations',
            field=models.ManyToManyField(blank=True, related_name='instructor_users', to='courses.specialization'),
        ),
        migrations.AddField(
            model_name='user',
            name='instructor_subspecializations',
            field=models.ManyToManyField(blank=True, related_name='instructor_users', to='courses.subspecialization'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_departments',
            field=models.ManyToManyField(blank=True, related_name='student_users', to='courses.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_specializations',
            field=models.ManyToManyField(blank=True, related_name='student_users', to='courses.specialization'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_subspecializations',
            field=models.ManyToManyField(blank=True, related_name='student_users', to='courses.subspecialization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('admin', 'Admin')], default='student', max_length=16),
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_parents', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
