# Generated by Django 5.2.5 on 2025-09-13 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_dob_user_gender_user_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='ParentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_email', models.EmailField(max_length=254)),
                ('child_name', models.CharField(blank=True, default='', max_length=120)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='child_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'child_email')},
            },
        ),
        migrations.CreateModel(
            name='InviteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_text', models.TextField(blank=True, default='')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.parentinvite')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
