"""
Django settings for eduvanta project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
try:
    # Load variables from the project .env into process environment
    from dotenv import load_dotenv  # type: ignore
    _env_loaded = load_dotenv(Path(__file__).resolve().parent.parent / '.env')
except Exception:
    # dotenv is optional; if it's not available, os.getenv will just read OS env
    _env_loaded = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.getenv('DJANGO_DEBUG', 'True')).lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Restored DRF app
    'rest_framework_simplejwt',  # Restored JWT app
    'channels',
    'accounts',
    'courses',
    'announcements',
    'gamification',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'eduvanta.middleware.ProfileSetupRedirectMiddleware',
    'gamification.middleware.StreakMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eduvanta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'accounts.context_processors.branding',
                'accounts.context_processors.notifications',
                'accounts.context_processors.user_xp',
            ],
        },
    },
]

WSGI_APPLICATION = 'eduvanta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database: prefer DATABASE_URL (e.g., postgres) else fallback to sqlite
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=False)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom user model for EduVanta
AUTH_USER_MODEL = 'accounts.User'

# Authentication backends for social auth + Django
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'accounts.auth_backends.AdminOnlyBackend',
    'accounts.auth_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""Email configuration
Reads SMTP settings from environment. When DEBUG is True and SMTP credentials are
missing, automatically falls back to the console email backend so development
is not blocked by SMTP errors.
"""
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = str(os.getenv('EMAIL_USE_TLS', 'True')).lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = str(os.getenv('EMAIL_USE_SSL', 'False')).lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Default backend can be overridden via env. Otherwise pick SMTP; if DEBUG and
# missing SMTP creds, use console backend.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
if DEBUG and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@localhost')

# AI Configuration (from environment)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
HF_TOKEN = os.getenv('HF_TOKEN')

# Platform Settings
PLATFORM_NAME = 'EduVanta'
CURRENT_YEAR = 2025
BASE_URL = 'http://localhost:8000'

# Branding defaults (DB overrides via SiteSetting)
SITE_BRAND_NAME = os.getenv('SITE_BRAND_NAME', 'EduVanta')
SITE_BRAND_COLOR = os.getenv('SITE_BRAND_COLOR', '#4f46e5')
SITE_BRAND_LOGO_URL = os.getenv('SITE_BRAND_LOGO_URL', '')
SITE_EMAIL_SUBJECT_PREFIX = os.getenv('SITE_EMAIL_SUBJECT_PREFIX', '[EduVanta]')

# ID Generation Settings (can be used in custom ID generators if needed)
STUDENT_ID_PREFIX = 'EDUS'
INSTRUCTOR_ID_PREFIX = 'EDUI'
PARENT_ID_PREFIX = 'EDUP'
ADMIN_ID_PREFIX = 'EDUA'

# Gamification Settings (add as constants or use in relevant models/views)
XP_ASSIGNMENT_COMPLETE = 20
XP_QUIZ_PASS = 15
XP_EARLY_SUBMISSION = 10
XP_COURSE_COMPLETE = 100

# Authentication backends for JWT + API throttling
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'anon': '200/day',
        'otp': '5/hour',
    },
}

# SimpleJWT token lifetimes
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# ASGI application for Channels
ASGI_APPLICATION = 'eduvanta.asgi.application'

# Channels Redis layer (enable when Redis available)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')],
        },
    }
}

# Celery (dev defaults)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)

# Social Auth provider credentials (use environment variables in development/production)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

SOCIAL_AUTH_FACEBOOK_KEY = os.getenv('SOCIAL_AUTH_FACEBOOK_KEY')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('SOCIAL_AUTH_FACEBOOK_SECRET')

SOCIAL_AUTH_GITHUB_KEY = os.getenv('SOCIAL_AUTH_GITHUB_KEY')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('SOCIAL_AUTH_GITHUB_SECRET')

# Optional: define redirect URLs (defaults are fine, but explicit is clearer)
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ---- Admin-only login configuration (can be moved to .env) ----
# Default admin creds for quick setup; override in environment for security
ADMIN_ONLY_USERNAME = os.getenv('ADMIN_ONLY_USERNAME', 'EduVanta')
ADMIN_ONLY_EMAIL = os.getenv('ADMIN_ONLY_EMAIL', 'eduvanta001@gmail.com')
ADMIN_ONLY_PASSWORD = os.getenv('ADMIN_ONLY_PASSWORD', 'EduVanta')
