# Generated by Django 5.2.5 on 2025-09-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseinstructor_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=64, null=True)),
                ('duration', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='courses.department')),
            ],
            options={
                'ordering': ['department__code', 'order', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
    ]
