# Generated by Django 5.2.5 on 2025-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_tag_course_approval_status_course_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_xp',
            field=models.PositiveIntegerField(default=100, help_text='Maximum XP awarded for completing this course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='earned_xp',
            field=models.PositiveIntegerField(default=0, help_text='Cached XP earned for this course enrollment'),
        ),
    ]
